---
title: "Exercise 3"
output: html_document
date: "2024-09-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2.1

```{r}
Gamma <- matrix(c(0.1, 0.9, 0.4, 0.6), nrow = 2, byrow = T)
delta <- 1/1.3*c(0.4, 0.9)
lambda <- c(1, 3)
ObsSeq <- c(0,2,1)

#Path (1,1,1)

calc_path_probalities <- function(path)
{
  delta[path[1]]*exp(-lambda[path[1]])*lambda[path[1]]^ObsSeq[1]/factorial(ObsSeq[1])*Gamma[path[1],path[2]]*exp(-lambda[path[2]])*lambda[path[2]]^ObsSeq[2]/factorial(ObsSeq[2])*Gamma[1,1]*exp(-lambda[1])*lambda[1]^ObsSeq[3]/factorial(ObsSeq[3])
}



#Other paths are similar
```

```{r}
ForwardMatPoisson <- function(delta, Gamma, lambda, data = ObsSeq)
{
  m <- length(delta)
  capT <- length(data)
  
  alpha_mat <- matrix(numeric(m*capT), nrow = m, ncol = capT)
  
  alpha_mat[,1] <- delta*sapply(lambda, function(rate){dpois(data[1], rate)})
  for(t in 2:capT)
  {
    for(j in 1:m)
    {
      alpha_mat[j,t] <- sum(alpha_mat[,(t-1)]*Gamma[,j]*sapply(lambda, function(rate){dpois(data[t], rate)}))
    }
  }
  
  return(alpha_mat)
}

LikelihoodHMMPoisson <- function(delta, Gamma, lambda, data = ObsSeq)
{
  capT <- length(data)
  
  alpha_mat <- ForwardMatPoisson(delta, Gamma, lambda, data)
  return(sum(alpha_mat[,capT]))
}
```

```{r}
ForwardMatPoisson(delta, Gamma, lambda)
LikelihoodHMMPoisson(delta, Gamma, lambda)
```


Important question: What happens to the forward probabilities if T becomes large?

```{r}
capT <- 400
ObsSeq <- numeric(capT)
HiddenStates <- numeric(capT)
HiddenStates[1] <- sample(1:2, 1, prob = delta)
ObsSeq[1] <- rpois(1, lambda[HiddenStates[1]])
for(t in 2:capT)
{
  HiddenStates[t] <- sample(1:2, 1, prob = Gamma[HiddenStates[(t-1)],])
  ObsSeq[t] <- rpois(1, lambda[HiddenStates[t]])
}
```

```{r}
LikelihoodHMMPoisson(delta, Gamma, lambda)
```
How do we accomodate this?

```{r}
prob_mat_poisson <- function(emission, lambda)
{
  return(diag(as.numeric(outer(emission, lambda, dpois))))
}

likelihood_calc_avoiding_underflow <- function(Gamma, delta, lambda, data = ObsSeq)
{
  m <- length(delta)
  capT <- length(data)
  
  phi_mat <- matrix(numeric(m*(capT+1)), nrow = m, ncol = capT+1)
  phi_mat[,1] <- delta
  logLk <- 0
  for(t in 2:(capT+1))
  {
    v <- t(phi_mat[,(t-1)])%*%Gamma%*%prob_mat_poisson(data[(t-1)], lambda)
    u <- sum(v)
    logLk <- logLk + log(u)
    phi_mat[,t] <- v/u
  }
  
  return(logLk)
}
```

```{r}
likelihood_calc_avoiding_underflow(Gamma, delta, lambda)
```

```{r}
likelihood_for_numeric_optim <- function(thetas, data = ObsSeq)
{
  p <- length(thetas) #Total number of parameters should be equal to m*(m-1) + m-1 + m = m^2 + m-1
  m <- (-1+sqrt(5+4*p))/2
  capT <- length(data)
  
  lambdas <- exp(thetas[1:m])
  delta <- c(1, exp(thetas[(m+1):(2*m-1)]))
  delta <- delta/sum(delta)
  Gamma <- matrix(numeric(m^2), nrow = m)
  for(i in 1:m)
  {
    Gamma[i,] <- c(1, exp(thetas[((i+1)*(m-1) + 2):((i+2)*(m-1)+1)]))
    Gamma[i,] <- Gamma[i,]/sum(Gamma[i,])
  }
  
  phi_mat <- matrix(numeric(m*(capT+1)), nrow = m, ncol = capT+1)
  phi_mat[,1] <- delta
  
  #cat("lambdas:", lambdas, "delta:", delta, "Gamma", Gamma, "\n")

  logLk <- 0
  for(t in 2:(capT+1))
  {
    v <- t(phi_mat[,(t-1)])%*%Gamma%*%prob_mat_poisson(data[(t-1)], lambdas)
    u <- sum(v)
    logLk <- logLk + log(u)
    phi_mat[,t] <- v/u
  }
  
  return(-logLk)
}
```

```{r}
ObsSeq <- c(13,14,8,10,16,26,32,27,18,32,36,24,22,23,22,18,25,21,
            21,14,8,11,14,23,18,17,19,20,22,19,13,26,13,14,22,24,
            21,22,26,21,23,24,27,41,31,27,35,26,28,36,39,21,17,22,
            17,19,15,34,10,15,22,18,15,20,15,22,19,16,30,27,29,23,
            20,16,21,21,25,16,18,15,18,14,10,15,8,15,6,11,8,7,18,
            16,13,12,13,20,15,16,12,18,15,16,13,15,16,11,11)
m <- 3
thetas_init <- c(log(30), log(20), log(10), 0.7, 0.8, -1, -1, 2, -2, 2, 5)

optimized <- optim(thetas_init, likelihood_for_numeric_optim)
```

```{r}
transform_back <- function(thetas)
{
  p <- length(thetas) #Total number of parameters should be equal to m*(m-1) + m-1 + m = m^2 + m-1
  m <- (-1+sqrt(5+4*p))/2
  
  lambdas <- exp(thetas[1:m])

  delta <- c(1, exp(thetas[(m+1):(2*m-1)]))
  delta <- delta/sum(delta)
  
  Gamma <- matrix(numeric(m^2), nrow = m)
  for(i in 1:m)
  {
    Gamma[i,] <- c(1, exp(thetas[((i+1)*(m-1) + 2):((i+2)*(m-1)+1)]))
    Gamma[i,] <- Gamma[i,]/sum(Gamma[i,])
  }
  
  return(list("lambda" = lambdas, "delta" = delta, "Gamma" = Gamma))
}
```



```



